# Generated by Django 5.2.9 on 2026-01-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('str', 'String')], default='str', max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='dashboardapp.machine')),
            ],
        ),
    ]
